"""Phase 1 — database model tests.

Verifies that all five SQLModel tables are correctly registered with metadata
and can be created in an in-memory SQLite database without errors.
"""
import pytest
from sqlalchemy import inspect
from sqlmodel import Session, SQLModel, create_engine

from app.models.db import (
    AuthProvider,
    Deal,
    DealVerdict,
    Report,
    User,
)


@pytest.fixture(scope="module")
def fresh_engine():
    """Module-scoped in-memory engine with all tables created."""
    engine = create_engine("sqlite://", connect_args={"check_same_thread": False})
    SQLModel.metadata.create_all(engine)
    yield engine
    SQLModel.metadata.drop_all(engine)


def test_all_five_tables_exist(fresh_engine):
    """All expected tables must be present after create_all."""
    inspector = inspect(fresh_engine)
    existing = set(inspector.get_table_names())
    expected = {"users", "auth_providers", "deals", "deal_verdicts", "reports"}
    assert expected.issubset(existing), (
        f"Missing tables: {expected - existing}"
    )


def test_users_table_columns(fresh_engine):
    inspector = inspect(fresh_engine)
    cols = {c["name"] for c in inspector.get_columns("users")}
    assert {"id", "email", "display_name", "is_active", "created_at"}.issubset(cols)


def test_auth_providers_table_columns(fresh_engine):
    inspector = inspect(fresh_engine)
    cols = {c["name"] for c in inspector.get_columns("auth_providers")}
    assert {"id", "user_id", "provider", "provider_user_id", "hashed_credential"}.issubset(cols)


def test_deals_table_has_json_deal_data(fresh_engine):
    inspector = inspect(fresh_engine)
    cols = {c["name"]: c for c in inspector.get_columns("deals")}
    assert "deal_data" in cols, "deals table must have a deal_data column"


def test_deal_verdicts_table_columns(fresh_engine):
    inspector = inspect(fresh_engine)
    cols = {c["name"] for c in inspector.get_columns("deal_verdicts")}
    assert {"id", "deal_id", "verdict_status", "dscr", "cap_rate", "monthly_cash_flow"}.issubset(cols)


def test_reports_table_columns(fresh_engine):
    inspector = inspect(fresh_engine)
    cols = {c["name"] for c in inspector.get_columns("reports")}
    assert {"id", "user_id", "deal_id", "report_type", "payload"}.issubset(cols)


def test_users_email_index_is_unique(fresh_engine):
    inspector = inspect(fresh_engine)
    indexes = inspector.get_indexes("users")
    email_indexes = [i for i in indexes if "email" in i["column_names"]]
    assert any(i["unique"] for i in email_indexes), (
        "users.email must have a unique index"
    )


def test_user_model_instantiation():
    """User dataclass can be created with required fields."""
    user = User(email="test@example.com", display_name="Test User")
    assert user.email == "test@example.com"
    assert user.is_active is True
    assert user.id is not None  # UUID generated by default_factory


def test_deal_model_defaults():
    """Deal defaults to 'analysis' status."""
    from app.models.db.deal import DealStatus
    deal = Deal(user_id="some-uuid", address="123 Main St")
    assert deal.status == DealStatus.analysis


def test_tables_are_reversible(fresh_engine):
    """drop_all followed by create_all must succeed without errors."""
    SQLModel.metadata.drop_all(fresh_engine)
    SQLModel.metadata.create_all(fresh_engine)
    inspector = inspect(fresh_engine)
    assert "users" in inspector.get_table_names()
