"""initial_schema

Revision ID: 50287f78097c
Revises: 
Create Date: 2026-05-11 19:02:59.337311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50287f78097c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('auth_providers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sa.Enum('password', 'google', 'microsoft', name='providertype'), nullable=False),
    sa.Column('provider_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_credential', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_providers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_providers_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_providers_provider_user_id'), ['provider_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_providers_user_id'), ['user_id'], unique=False)

    op.create_table('deals',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', sa.Enum('analysis', 'under_contract', 'closed', 'rejected', 'deleted', name='dealstatus'), nullable=False),
    sa.Column('deal_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_user_id'), ['user_id'], unique=False)

    op.create_table('deal_verdicts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verdict_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('monthly_cash_flow', sa.Float(), nullable=False),
    sa.Column('dscr', sa.Float(), nullable=False),
    sa.Column('cap_rate', sa.Float(), nullable=False),
    sa.Column('cash_on_cash_return', sa.Float(), nullable=False),
    sa.Column('total_cash_required', sa.Float(), nullable=False),
    sa.Column('noi', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_verdicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_verdicts_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_verdicts_id'), ['id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_id'))
        batch_op.drop_index(batch_op.f('ix_reports_deal_id'))

    op.drop_table('reports')
    with op.batch_alter_table('deal_verdicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_verdicts_id'))
        batch_op.drop_index(batch_op.f('ix_deal_verdicts_deal_id'))

    op.drop_table('deal_verdicts')
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_user_id'))
        batch_op.drop_index(batch_op.f('ix_deals_status'))
        batch_op.drop_index(batch_op.f('ix_deals_id'))

    op.drop_table('deals')
    with op.batch_alter_table('auth_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_providers_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_providers_provider_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_providers_provider'))
        batch_op.drop_index(batch_op.f('ix_auth_providers_id'))

    op.drop_table('auth_providers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
